{% set version = "2.9.0" %}
{% set build = 1002 %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: 49d593c07a3a4cb87ed421f502e34368b98282a4ac6d4388379aab80b11c7924

build:
  number: {{ build }}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `hdf5 * mpi_*` for any mpi
  # `hdf5 * nompi_*` for no mpi
  string: "mpi_py{{ py }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python
    - pip
    - numpy x.x
    - mpi4py
    - cython
    - six
    - pkgconfig
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mpi4py
    - six

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python

extra:
  recipe-maintainers:
     - smutch
  original-recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - ocefpaf
    - minrk
